### ISSUE TITLE
增加中文水印无法显示

### ISSUE THREAD

**Issue by wjhbj** [danpe1327/CheeseTool#2]
所用代码：python .\add_watermark.py .\s1.docx --watermark '网信办'
 
![1583830044(1)](https://user-images.githubusercontent.com/17037270/76295001-d98f3100-62ee-11ea-8ab1-fc5c7dc79f91.png)

**Comment by wjhbj** [comment]
![1583830044(1)](https://user-images.githubusercontent.com/17037270/76295056-edd32e00-62ee-11ea-9044-deab61ad7190.png)

**Comment by wjhbj** [comment]
显示的是黑色的方块，

**Comment by danpe1327** [comment]
需要更换其他带中文的字体

**Comment by danpe1327** [comment]
已经更新了说明，请重新试一下

**Comment by wjhbj** [comment]
还是不行，我运行了下：
python add_watermark.py .\s1.docx --watermark '网信办' --font_file 'SIMYOU.TTF'
还是黑块，
然后在add_watermark.py里面添加了
 print(font_file)
 print(os.path.exists(font_file))
 print(os.path.curdir)
输出分别为：
'SIMYOU.TTF'
False
.
我的操作系统是Win10 64位，python新手，

**Comment by danpe1327** [comment]
用我上传的字体呢？黑体或者宋体。

**Comment by danpe1327** [comment]
你的代码路径下没有字体文件吗？

**Comment by wjhbj** [comment]
必须把字体文件放在代码路径下吗？不是自动识别系统的windows下面的fonts里面的啊

**Comment by wjhbj** [comment]
谢谢，
import sys
import os

dirpath = os.path.dirname(os.path.abspath(__file__))
os.chdir(dirpath)
command="python add_watermark.py .\s1.docx --watermark '网信办' --font_file fs2312.ttf"

os.system(command)
成功了，我把字体文件拷贝到了代码文件夹下，字体文件不能加引号
