### ISSUE TITLE
希望能被看到

### ISSUE THREAD

**Issue by User15022** [danpe1327/CheeseTool#3]
按照提示安装PDF工具包之后from pypdf import PdfFileReader, PdfFileWriter，这里还是出错，把pypdf改成PyPDF2之后，运行显示错误failed to add watermark E:\test\test1.doc __init__() takes 1 positional argument but 2 were given

**Comment by danpe1327** [comment]
能把运行的命令和完整的错误页面贴上来吗？

**Comment by User15022** [comment]
我的QQ是2958539369，大佬能加我私聊吗？

**Comment by User15022** [comment]
谢谢大佬的耐心帮助，人也很好
